on:
  workflow_run:
    workflows:
      - Check and Lint
    types:
      - completed
  workflow_dispatch:

name:
  Pull and Restart

jobs:
  pull_restart:
    name: pull restart
    runs-on: ubuntu-latest

    steps:
      - name: install ssh keys
        run: |
            install -m 600 -D /dev/null ~/.ssh/id_rsa
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      - name: connect, pull, recompile and restart
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git checkout ${{ secrets.MAIN_BRANCH }} && git reset --hard HEAD^ && git pull && ${{ secrets.CARGO }} build --release && systemctl restart ${{ secrets.SERVICE_NAME }}"
      - name: cleanup
        run: rm -rf ~/.ssh
